package cz.metlicka.server.builderjilt;

import lombok.RequiredArgsConstructor;
import org.jilt.Builder;
import org.jilt.BuilderStyle;

import java.time.LocalDateTime;

@Builder(style = BuilderStyle.TYPE_SAFE_UNGROUPED_OPTIONALS)
@RequiredArgsConstructor
public class JustSomeRandomPojoWithMandatoryFields {

    private final String mandatoryString1;

    private final String mandatoryString2;

    private final String mandatoryString3;

    private final int mandatoryInt4;

    private final long mandatoryLong5;

    private final LocalDateTime mandatoryLocalDateTime6;

    private JustSomeRandomPojoWithMandatoryFields exampleOfJiltBuilder() {
        //This is an example of a type-safe builder generated by Jilt. Notice that you cannot
        //build the pojo without using all the builder steps.
        return JustSomeRandomPojoWithMandatoryFieldsBuilder
                .justSomeRandomPojoWithMandatoryFields()
                .mandatoryString1("mandatory1")
                .mandatoryString2("mandatory2")
                .mandatoryString3("mandatory3")
                .mandatoryInt4(123)
                .mandatoryLong5(123L)
                .mandatoryLocalDateTime6(LocalDateTime.now())
                .build();
    }

}
